# Generated by Django 3.2.6 on 2023-01-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('alpha_2', models.TextField(blank=True, db_column='Alpha_2', null=True)),
                ('alpha_3', models.TextField(blank=True, db_column='Alpha_3', null=True)),
                ('numeric_code', models.TextField(blank=True, null=True)),
                ('latitude_average', models.TextField(blank=True, null=True)),
                ('longitude_average', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emissions_countries',
                'managed': False,
            },
        ),
    ]
