# Generated by Django 3.2.6 on 2023-01-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('population', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cities2_cities2',
            },
        ),
    ]
